# This file contains the [pre-commit](https://pre-commit.com/) configuration of this repository.
# More on which specific pre-commit hooks we use can be found in README.md.
---
minimum_pre_commit_version: "2.9.2"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.3" # Can not be removed, so leave this empty.
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: isort
        name: iSort - Sorts imports.
        description: Sorts your import for you.
        entry: isort
        language: python
        types: [python]
        require_serial: true
        additional_dependencies:
          - isort
      #      - id: black
      #        name: Black - Auto-formatter.
      #        description: Black is the uncompromising Python code formatter. Writing to files.
      #        entry: black
      #        language: python
      #        types: [python]
      #        require_serial: true
      #        additional_dependencies:
      #          - black
      - id: flake8
        name: Flake8 - Enforce code style and doc.
        description: A command-line utility for enforcing style consistency across Python projects.
        entry: flake8
        args: ["--config=.flake8"]
        language: python
        types: [python]
        exclude: ^examples/|^tests/
        require_serial: true
        additional_dependencies:
          - flake8
          - flake8-docstrings
      - id: mypy
        name: mypy - Static type checking
        description: Mypy helps ensure that we use our functions and variables correctly by checking the types.
        entry: mypy
        language: system
        types: [python]
        exclude: ^examples/
        require_serial: true
